version: "3.8"

# run
# docker-compose -f <PROJECT_PATH>/quarkus-sampler/etc/docker-compose/docker-compose.local.weather-service.yml up --build --force-recreate
#
# run from project directory
# docker-compose -f ./etc/docker-compose/docker-compose.local.weather-service.yml up --build --force-recreate
#
# enter container
# docker exec -it weather-service-dev /bin/bash
#
# empty run
# docker run --rm -it weather-service:develop-local /bin/bash
services:
    weather-service:
        container_name: weather-service-dev
        build:
            context: ../../
            dockerfile: etc/docker-compose/local.fast-jar.Dockerfile
            args:
                ICELL_JAVA_JRE_BASE_IMAGE: 'icellmobilsoft/base-java21jre:1.4.0'
                SERVICE: 'weather-service'
        image: "weather-service:develop-local"
        environment:
            # With this config, service use application-dev.yml!
            # - MP_CONFIG_PROFILE=dev
        ports:
            - '8080:8080' # REST
            - '5005:5005' # Debug
            - '9001:9001' # Management
        deploy:
            resources:
                limits:
                    memory: 512M
                reservations:
                    memory: 512M
networks:
    default:
        external:
            # if it could not be found on compose up, then execute: docker network create weather-local-network
            name: weather-local-network
