#version: "3.8"

# run
# docker compose -f <PROJECT_PATH>/etc/docker-compose/docker-compose.local.native.weather-service.yml up --build --force-recreate
#
# run from project directory
# docker compose -f ./etc/docker-compose/docker-compose.local.native.weather-service.yml up --build --force-recreate
#
# enter container
# docker exec -weather-service-dev-native /bin/bash
#
# empty run
# docker run --rm -it weather-service:develop-local-native /bin/bash
services:
    weather-service:
        container_name: weather-service-dev-native
        build:
            context: ../../
#            dockerfile: etc/docker-compose/local.native-jar.Dockerfile
            dockerfile: etc/docker-compose/local.native-micro-image.Dockerfile
            args:
                ICELL_JAVA_JRE_BASE_IMAGE: 'icellmobilsoft/base-java21jre:1.4.0'
                SERVICE: 'weather-service'
        image: "weather-service:develop-local-native"
        environment:
            # With this config, service use application-dev.yml!
            - MP_CONFIG_PROFILE=dev
        ports:
            - '8080:8080' # REST
            - '5005:5005' # Debug
            - '9001:9001' # Management
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 512M
                reservations:
                    cpus: '1'
                    memory: 512M
networks:
    default:
        external:
            # if it could not be found on compose up, then execute: docker network create quarkus-sampler-local-network
            name: weather-local-network
