#-------------------------------
# Quarkus datasource settings
# mvn quarkus:dev -Dquarkus.profile=postgresql
# clean install -Dquarkus.profile=postgresql
#-------------------------------

quarkus:
  datasource:
    metrics:
      enabled: true
    "defaultDS":
      jdbc:
        min-size: 5
        max-size: 20
        # Ha nincs url, automatikusan indítja a dev servicet
        url: ""
      db-kind: postgresql
      username: quarkus
      password: quarkus
  hibernate-orm:
    packages: com.github.speter555.weather.model,hu.icellmobilsoft.coffee.model.base
    dialect: org.hibernate.dialect.PostgreSQLDialect
    database:
      generation: drop-and-create
    log:
      #queries-slower-than-ms: 500
      format-sql: true
      sql: true
      #bind-parameters: true
    jdbc:
      timezone: UTC
    mapping:
      timezone:
        default-storage: normalize-utc