#-------------------------------
# Maven config
#-------------------------------
coffee:
  app:
    projectStage: dev
quarkus:
  datasource:
    metrics:
      enabled: true
  log:
    level: INFO
    min-level: ALL
  swagger-ui:
    enable: true


