#-------------------------------
# Coffee config
#-------------------------------
coffee:
  app:
    name: ${quarkus.application.name}
  config:
    datasource:
      default:
        name: defaultDS
    resource:
      bundles: i18n.messages
    xml:
      catalog:
        path: xsd/com/github/speter555/weather/dto/super.catalog.xml

mp:
  openapi:
    filter: com.github.speter555.weather.common.rest.filter.OpenAPIFilter

#-------------------------------
# Quarkus settings
#-------------------------------
quarkus:
  datasource:
    "defaultDS":
      jdbc:
        min-size: 5
        max-size: 20
        url: jdbc:h2:mem:default
      db-kind: h2
  management:
    enabled: true
    port: 9001
  hibernate-orm:
    packages: com.github.speter555.weather.model,hu.icellmobilsoft.coffee.model.base
    datasource: "defaultDS"
    dialect: org.hibernate.dialect.H2Dialect
    database:
      generation: drop-and-create
    log:
      #queries-slower-than-ms: 500
      format-sql: true
      sql: true
      #bind-parameters: true
    jdbc:
      timezone: UTC
    mapping:
      timezone:
        default-storage: normalize-utc
  arc:
#    remove-unused-beans: false
    remove-unused-beans: true
    unremovable-types:
      - hu.icellmobilsoft.coffee.module.csv.**
      - org.apache.deltaspike.data.impl.handler.QueryHandler
      - hu.icellmobilsoft.coffee.tool.utils.stream.LoggingPublisher
      - hu.icellmobilsoft.coffee.rest.validation.xml.utils.XsdHelper
      - hu.icellmobilsoft.coffee.rest.validation.xml.error.XsdValidationErrorCollector
      - hu.icellmobilsoft.coffee.rest.validation.catalog.PublicCatalogResolver
      - hu.icellmobilsoft.coffee.tool.utils.stream.LoggingPublisher
      - hu.icellmobilsoft.coffee.module.mp.restclient.provider.DefaultLoggerClientRequestFilter
      - hu.icellmobilsoft.coffee.module.mp.restclient.provider.DefaultLoggerClientResponseFilter
      - hu.icellmobilsoft.coffee.module.mp.restclient.provider.DefaultSettingClientRequestFilter
      - hu.icellmobilsoft.coffee.module.mp.restclient.provider.DefaultBaseExceptionResponseExceptionMapper
  log:
    category:
      "com.github.speter555":
        level: ${LOG_COM_GITHUB_SPETER555_LEVEL:INFO}
      "hu.icellmobilsoft":
        level: ${LOG_HU_ICELLMOBILSOFT_LEVEL:INFO}
    console:
      format: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p [traceId=%X{traceId}] [spanId=%X{spanId}] [thread:%t] [%c{10}] [sid:%X{extSessionId}] - %s%E%n"
    level: ${LOG_LEVEL:INFO}
    min-level: ${LOG_MIN_LEVEL:ALL}
  rest-client:
    "com.github.speter555.weather.restclient.wttrinapi.WttrInRestClient":
      url: https://wttr.in
      scope: jakarta.enterprise.context.ApplicationScoped
      #read-timeout: 5000
      #connect-timeout: 5000
  package:
    jar:
      type: fast-jar
      add-runner-suffix: false
  smallrye-openapi:
    info-title: Weather service
    info-version: ${quarkus.application.version}
    info-description: >
      REST endpoints for operations. <br/> 
      General responses in case of error:  <br/> 
      * __400__ - Bad Request <br/> 
      * __401__ - Unauthorized <br/> 
      * __404__ - Not found <br/> 
      * __418__ - Database object not found <br/> 
      * __500__ - Internal Server Error <br/>
  swagger-ui:
    enable: false

